### ISSUE TITLE
[github-actions] posix-pty fails frequently

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#5648]
**Describe the bug** A clear and concise description of what the bug is.

posix-pty fails frequently.

**Console/log output** If applicable, add console/log output to help explain your problem.

```
Keep POSIX Only
Run rm -rf build/x86_64-unknown-linux-gnu/
  rm -rf build/x86_64-unknown-linux-gnu/
  tar -xf build/posix.tar -C build/
  shell: /bin/bash -e {0}
  env:
    COVERAGE: 1
tar: posix/x86_64-unknown-linux-gnu/third_party/Makefile: Cannot open: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries: Cannot mkdir: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/utf_converter: Cannot mkdir: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/utf_converter/.deps: Cannot mkdir: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/utf_converter/.deps/libnordicsemi_nrf52840_sdk_a-utf.Po: Cannot open: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/utf_converter/.deps/libnordicsemi_nrf52811_sdk_a-utf.Po: Cannot open: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/utf_converter/.deps/libnordicsemi_nrf52833_sdk_a-utf.Po: Cannot open: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/usb: Cannot mkdir: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/usb/.deps: Cannot mkdir: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/usb/.deps/libnordicsemi_nrf52833_sdk_a-nrf_dfu_trigger_usb.Po: Cannot open: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/usb/.deps/libnordicsemi_nrf52833_sdk_a-app_usbd_nrf_dfu_trigger.Po: Cannot open: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/usb/.deps/libnordicsemi_nrf52833_sdk_a-app_usbd.Po: Cannot open: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/usb/.deps/libnordicsemi_nrf52840_sdk_a-app_usbd_serial_num.Po: Cannot open: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/usb/.deps/libnordicsemi_nrf52840_sdk_a-app_usbd_string_desc.Po: Cannot open: No such file or directory
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor: Cannot mkdir: Permission denied
tar: posix/x86_64-unknown-linux-gnu/third_party/NordicSemiconductor/libraries/usb/.deps/libnordicsemi_nrf52833_sdk_a-app_usbd_core.Po: Cannot open: No such file or directory
...
```

[logs_3077.zip](https://github.com/openthread/openthread/files/5379283/logs_3077.zip)
