### ISSUE TITLE
there are duplicate data in network diagnostic results

### ISSUE THREAD

**Issue by LancerSky** [openthread/openthread#7448]
**Describe the bug** A clear and concise description of what the bug is.
Hello, the network diagnostic command returned duplicate data in 'Child Table',
both 'ChildId: 0x0002' and 'ChildId: 0x0003' appear twice. Is this right?
```
root@OpenWrt:/tmp# ot-ctl networkdiagnostic get ff03::2 0 1 2 3 4 5 6 7 8 9 14 15 16 17 18 19
DIAG_GET.rsp/ans from fdd2:b178:8ba5:0:0:ff:fe00:3000: 00083e7229d432a393c70102300002010f040a00000000005801050001050a5800080000000000000106085de700f040bc830c073708040b026bed03140040fd11002200000000050430003100070211400b1980015d0d143000fdd2b1788ba500009e810437eaf12146d11f0860fdd2b1788ba50000000000fffe00fc10fd11002200000000eb3b59773b097287fdd2b1788ba50000000000fffe00fc00fdd2b1788ba50000000000fffe003000fdd2b1788ba500009e810437eaf12146fe800000000000003c7229d432a393c70924000000000000000300000004000001550000006100000000000001100000004300000004106060020c60030c60050c60080c600d0c600e0c600f0c60110c60150c60190c601a0c601b0c601c0c60040c60010c601f0c60000c60010c60020c60030c60040c60050c60060c60070c60080c60090c600a0c600b0c600c0c600d0c600e0c600f0c1101001304000000f0
Ext Address: '3e7229d432a393c7
Rloc16: 0x3000
Mode:
    RxOnWhenIdle: 1
    DeviceType: 1
    NetworkData: 1
Connectivity:
    ParentPriority: 0
    LinkQuality3: 0
    LinkQuality2: 0
    LinkQuality1: 0
    LeaderCost: 0
    IdSequence: 88
    ActiveRouters: 1
    SedBufferSize: 1280
    SedDatagramCount: 1
Route:
    IdSequence: 88
    RouteData:
        - RouteId: 0x0c
          LinkQualityOut: 0
          LinkQualityIn: 0
          RouteCost: 1
Leader Data:
    PartitionId: 0x5de700f0
    Weighting: 64
    DataVersion: 188
    StableDataVersion: 131
    LeaderRouterId: 0x0c
Network Data: '08040b026bed03140040fd11002200000000050430003100070211400b1980015d0d143000fdd2b1788ba500009e810437eaf12146d11f
IP6 Address List:
    - fdd2:b178:8ba5:0:0:ff:fe00:fc10
    - fd11:22:0:0:eb3b:5977:3b09:7287
    - fdd2:b178:8ba5:0:0:ff:fe00:fc00
    - fdd2:b178:8ba5:0:0:ff:fe00:3000
    - fdd2:b178:8ba5:0:9e81:437:eaf1:2146
    - fe80:0:0:0:3c72:29d4:32a3:93c7
MAC Counters:
    IfInUnknownProtos: 0
    IfInErrors: 3
    IfOutErrors: 4
    IfInUcastPkts: 341
    IfInBroadcastPkts: 97
    IfInDiscards: 0
    IfOutUcastPkts: 272
    IfOutBroadcastPkts: 67
    IfOutDiscards: 4
Child Table:
    - ChildId: 0x0002
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0003
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0005
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0008
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000d
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000e
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000f
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0011
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0015
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0019
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x001a
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x001b
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x001c
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0004
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0001
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x001f
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0000
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0001
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0002
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0003
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0004
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0005
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0006
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0007
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0008
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x0009
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000a
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000b
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000c
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000d
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000e
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
    - ChildId: 0x000f
      Timeout: 12
      Mode:
          RxOnWhenIdle: 1
          DeviceType: 0
          NetworkData: 0
Channel Pages: '00'
Max Child Timeout: 240
Done

```
**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id https://github.com/openthread/ot-br-posix/commit/a965a7535dad33303585d2080437f3d796e54a81
2. IEEE 802.15.4 hardware platform
3. Build steps
4. Network topology

**Expected behavior** A clear and concise description of what you expected to happen.

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.
